"use client";
import Image from "next/image";
import { useEffect,useState } from "react";
import { groupStandings,type Score,type Baker } from "@/lib/next-standings";
import { seasonName,teamName } from "@/lib/next-season";

export default function Home(){
 const [scores,setScores]=useState<Score[]>([]),[bakers,setBakers]=useState<Baker[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;fetch("/api/next-results",{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);if(active){setScores(data.scores);setBakers(data.baker);setLoading(false)}}).catch(e=>{if(active){setError(e instanceof Error?e.message:"Ergebnisse nicht erreichbar.");setLoading(false)}});return()=>{active=false}},[]);
 return <div className="shell"><header className="topbar"><a className="brand" href="/" aria-label="Bowlingcenter Oberberg – Startseite"><Image className="brand-logo" src="/bowlingcenter-oberberg.png" width={564} height={139} alt="Bowlingcenter Oberberg" priority /></a><div className="season-chip">{seasonName}</div></header><main className="container next-season"><div className="next-top"><div><p className="eyebrow">SAISON 2026/2027</p><h1>Tabellen</h1><p>Gruppe 1 und Gruppe 2 · Hin- und Rückrunde</p></div></div><nav className="public-nav" aria-label="Hauptnavigation"><a href="/kommende-saison">Spielplan und Ergebnisse</a><a href="/bestenliste">Bestenliste und Einzelspieler</a><a href="/finale">Finale</a><a href="/archiv/2025-26">Archiv 2025/26</a><a href="/eingabe">Ergebnisse eingeben</a></nav>{error?<p role="alert">{error}</p>:loading?<p>Lade Tabellen …</p>:<section className="next-standings"><div className="next-standings-list">{[1,2].map(group=><div className="next-group-table" key={group}><h2>Gruppe {group}</h2><div className="table-wrap"><table><thead><tr><th>Platz</th><th>Mannschaft</th><th>Spiele</th><th>Punkte</th><th>Pins</th></tr></thead><tbody>{groupStandings(group,scores,bakers).map((team,index)=><tr key={team.id}><td>{index+1}</td><td className="bold">{teamName(team.id)}</td><td>{team.games}</td><td className="bold">{team.points}</td><td>{team.pins.toLocaleString("de-DE")}</td></tr>)}</tbody></table></div></div>)}</div><p className="context-note">Je Spiel: 2 Punkte für mehr Pins, bei Gleichstand je 1. Die höchste Gesamtpinzahl eines vollständigen Spieltags bringt weitere 2 Punkte, bei Gleichstand je 1. Der Freigegner erhält 0 Punkte.</p></section>}<footer>Bowlingcenter Oberberg · Hausliga</footer></main></div>
}
