"use client";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, CircleCheck, LockKeyhole, Save, Trophy, Users, RefreshCw } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import season from "@/lib/season.json";

type Slot = { name:string; scores:(number|null)[][] };
type Team = { id:number; name:string; group:number; slots:Slot[] };
type Override = { team_id:number;day:number;slot:number;name:string;game_1:number|null;game_2:number|null;game_3:number|null };
type Draft = { slot:number;name:string;games:(number|null)[] }[];
const base = season.teams as Team[];
const fmt = (n:number) => new Intl.NumberFormat("de-DE").format(n);
const date = (d:string) => new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${d}T12:00:00`));
function initialDraft(team:Team, day:number):Draft { return team.slots.map((s,slot)=>({slot,name:s.name,games:[...s.scores[day-1]]})); }
function pins(team:Team,day:number) {return team.slots.flatMap(s=>s.scores[day-1]).reduce<number>((a,v)=>a+(v??0),0);}
function count(team:Team,day:number) {return team.slots.flatMap(s=>s.scores[day-1]).filter(v=>v!==null).length;}

export default function Home() {
 const [day,setDay]=useState(10),[group,setGroup]=useState(1),[teamId,setTeamId]=useState(1);
 const [overrides,setOverrides]=useState<Override[]>([]),[draft,setDraft]=useState<Draft>([]),[canEdit,setCanEdit]=useState(false),[status,setStatus]=useState("Lade gespeicherte Ergebnisse …"),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const teams=useMemo(()=>base.map(t=>({...t,slots:t.slots.map((s,slot)=>({name:s.name,scores:s.scores.map((games,i)=>{const found=overrides.find(r=>r.team_id===t.id&&r.day===i+1&&r.slot===slot);return found?[found.game_1,found.game_2,found.game_3]:games;})}))})),[overrides]);
 const chosen=teams[teamId-1];
 useEffect(()=>{let active=true;fetch("/api/results",{cache:"no-store"}).then(async res=>{const data=await res.json() as {error?:string;rows:Override[];canEdit:boolean};if(!res.ok)throw new Error(data.error);if(active){setOverrides(data.rows);setStatus("");}}).catch(e=>{if(active)setStatus(e.message||"Ergebnisse nicht erreichbar.")});return()=>{active=false};},[]);
 useEffect(()=>{if(!dirty)setDraft(initialDraft(chosen,day).map(r=>{const o=overrides.find(x=>x.team_id===teamId&&x.day===day&&x.slot===r.slot);return o?{slot:r.slot,name:o.name,games:[o.game_1,o.game_2,o.game_3]}:r;}));},[chosen,day,teamId,overrides,dirty]);
 function switchTo(nextDay:number,nextTeam:number){if(dirty&&!window.confirm("Ungespeicherte Eingaben verwerfen?"))return;setDirty(false);setDay(nextDay);setTeamId(nextTeam);}
 function edit(slot:number,key:"name"|number,value:string){setDraft(prev=>prev.map(r=>r.slot!==slot?r:key==="name"?{...r,name:value}:{...r,games:r.games.map((v,i)=>i===key?(value===""?null:Number(value)):v)}));setDirty(true);setStatus("");}
 async function save(){setBusy(true);setStatus("");try{const response=await fetch("/api/results",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({teamId,day,rows:draft})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);setOverrides(prev=>[...prev.filter(r=>!(r.team_id===teamId&&r.day===day)),...draft.map(r=>({team_id:teamId,day,slot:r.slot,name:r.name,game_1:r.games[0],game_2:r.games[1],game_3:r.games[2]}))]);setDirty(false);setStatus("Ergebnisse gespeichert.");}catch(e){setStatus(e instanceof Error?e.message:"Speichern fehlgeschlagen.");}finally{setBusy(false)}}
 const stats=teams.flatMap(t=>t.slots.map((s,slot)=>{const values=s.scores.flat().filter((v):v is number=>v!==null);return {key:`${t.id}-${slot}`,name:overrides.find(x=>x.team_id===t.id&&x.slot===slot&&x.name)?.name||s.name,team:t.name,games:values.length,total:values.reduce((a,b)=>a+b,0),best:Math.max(0,...values)};})).filter(x=>x.name&&x.name!=="Blind"&&x.name!=="Baker"&&x.games).sort((a,b)=>b.total/b.games-a.total/a.games);
 const table=teams.filter(t=>t.group===group).map(t=>{const n=Array.from({length:10},(_,i)=>count(t,i+1)).reduce((a,b)=>a+b,0);const total=Array.from({length:10},(_,i)=>pins(t,i+1)).reduce((a,b)=>a+b,0);return {...t,total,games:n,average:n?total/n:0};}).sort((a,b)=>b.total-a.total);
 const selectedFixtures=season.fixtures.filter(f=>f.day===day&&f.group===group);
 return <div className="shell"><header className="topbar"><a className="brand" href="/" aria-label="Bowlingcenter Oberberg – Startseite"><Image className="brand-logo" src="/bowlingcenter-oberberg.png" width={564} height={139} alt="Bowlingcenter Oberberg" priority /></a><div className="header-sponsor"><span>Zunft Kölsch</span><Image src="/koelsch-sponsor.webp" width={1012} height={889} alt="Zunft Kölsch – Das Kölsch für hier." /></div></header>
 <main className="container"><a className="next-link" href="/kommende-saison">Saison 2026/2027 →</a><div className="page-heading"><div><p className="eyebrow">ERGEBNISDOKUMENTATION</p><h1>Die Hausliga <em>im Blick.</em></h1><p className="intro">Spieltage, Pinzahlen und Spielergebnisse der Saison {season.season}.</p></div><div className="heading-icon"><Trophy size={34}/></div></div>
 <Tabs defaultValue="spieltage" className="app-tabs"><TabsList className="nav" aria-label="Ansichten"><TabsTrigger value="spieltage"><CalendarDays size={17}/>Spieltage</TabsTrigger><TabsTrigger value="tabelle"><Trophy size={17}/>Tabelle</TabsTrigger><TabsTrigger value="spieler"><Users size={17}/>Spieler</TabsTrigger>{canEdit&&<TabsTrigger value="erfassen"><Save size={17}/>Erfassen</TabsTrigger>}</TabsList>
 <TabsContent value="spieltage"><div className="toolbar"><div className="stepper"><button aria-label="Vorheriger Spieltag" onClick={()=>setDay(Math.max(1,day-1))} disabled={day===1}><ChevronLeft size={19}/></button><div><small>SAISON {season.season}</small><strong>Spieltag {day}</strong></div><button aria-label="Nächster Spieltag" onClick={()=>setDay(Math.min(10,day+1))} disabled={day===10}><ChevronRight size={19}/></button></div><GroupSelect group={group} setGroup={setGroup}/></div><div className="date-line"><CalendarDays size={17}/>{date(season.dates[day-1][group-1])}<span className="separator"/>Gruppe {group}</div><div className="fixture-grid">{selectedFixtures.map((f,i)=>{const home=teams[f.home-1],away=teams[f.away-1],p1=pins(home,day),p2=pins(away,day),c1=count(home,day),c2=count(away,day);return <article className="match-card" key={`${f.home}-${f.away}`}><div className="card-head"><span>BEGEGNUNG {String(i+1).padStart(2,"0")}</span><span className={c1||c2?"pill done":"pill"}>{c1||c2?"Ergebnisse vorhanden":"Noch offen"}</span></div><div className="match-line"><span className="team-name">{home.name}</span><strong>{c1?fmt(p1):"–"}</strong></div><div className="match-line"><span className="team-name">{away.name}</span><strong>{c2?fmt(p2):"–"}</strong></div><div className="card-foot">{c1+c2} Einzelspiele erfasst</div></article>})}</div><p className="context-note">Pinzahlen ergeben sich aus den erfassten Einzelspielen. Fehlende Werte bleiben offen.</p></TabsContent>
 <TabsContent value="tabelle"><div className="section-top"><div><p className="eyebrow">SAISON {season.season}</p><h2>Mannschaften</h2></div><GroupSelect group={group} setGroup={setGroup}/></div><div className="table-wrap"><table><thead><tr><th>Platz</th><th>Mannschaft</th><th>Spiele</th><th>Pins</th><th>Ø Pins</th></tr></thead><tbody>{table.map((t,i)=><tr key={t.id}><td><span className={i<3?"rank top":"rank"}>{String(i+1).padStart(2,"0")}</span></td><td className="bold">{t.name}</td><td>{t.games}</td><td className="bold">{fmt(t.total)}</td><td>{t.average?new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(t.average):"–"}</td></tr>)}</tbody></table></div><p className="context-note">Sortiert nach erfassten Pins. „Spiele“ zählt einzelne Spielergebnisse; unvollständige Spieltage sind enthalten.</p></TabsContent>
 <TabsContent value="spieler"><div className="section-top"><div><p className="eyebrow">SAISON {season.season}</p><h2>Spielerübersicht</h2></div><span className="small-counter">{stats.length} Spieler</span></div><div className="table-wrap"><table><thead><tr><th>Platz</th><th>Spieler</th><th>Mannschaft</th><th>Spiele</th><th>Pins</th><th>Ø Pins</th><th>Bestes</th></tr></thead><tbody>{stats.map((p,i)=><tr key={p.key}><td><span className={i<3?"rank top":"rank"}>{String(i+1).padStart(2,"0")}</span></td><td className="bold">{p.name}</td><td>{p.team}</td><td>{p.games}</td><td>{fmt(p.total)}</td><td className="bold">{new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(p.total/p.games)}</td><td>{p.best}</td></tr>)}</tbody></table></div><p className="context-note">Sortiert nach dem Durchschnitt aller vorhandenen Einzelspiele. Blind und Baker werden nicht als Spieler geführt.</p></TabsContent>
 {canEdit&&<TabsContent value="erfassen"><div className="section-top"><div><p className="eyebrow">NUR FÜR DEN ERFASSER</p><h2>Ergebnisse eintragen</h2></div><span className="editor-lock"><LockKeyhole size={15}/> Geschützte Eingabe</span></div><div className="entry-controls"><label>Spieltag<Select value={String(day)} onValueChange={v=>switchTo(Number(v),teamId)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:10},(_,i)=><SelectItem key={i} value={String(i+1)}>Spieltag {i+1}</SelectItem>)}</SelectContent></Select></label><label>Mannschaft<Select value={String(teamId)} onValueChange={v=>switchTo(day,Number(v))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{teams.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent></Select></label></div><div className="entry-card"><div className="entry-title"><div><strong>{chosen.name}</strong><span>Spieltag {day} · Gruppe {chosen.group}</span></div><div className="entry-total"><small>PINS GESAMT</small><strong>{fmt(draft.reduce((sum,r)=>sum+r.games.reduce<number>((s,v)=>s+(v??0),0),0))}</strong></div></div><div className="entry-list"><div className="entry-row labels"><span>SPIELER</span><span>SPIEL 1</span><span>SPIEL 2</span><span>SPIEL 3</span><span>SUMME</span></div>{draft.map(r=><div className="entry-row" key={r.slot}><input aria-label={`Spieler Zeile ${r.slot+1}`} className="name-input" value={r.name} onChange={e=>edit(r.slot,"name",e.target.value)} placeholder="Name" maxLength={80}/>{r.games.map((value,i)=><input key={i} aria-label={`${r.name||`Zeile ${r.slot+1}`} Spiel ${i+1}`} type="number" min="0" max="300" inputMode="numeric" value={value??""} onChange={e=>edit(r.slot,i,e.target.value)} placeholder="–"/>)}<strong>{r.games.some(x=>x!==null)?r.games.reduce<number>((a,v)=>a+(v??0),0):"–"}</strong></div>)}</div></div><div className="save-row"><p role="status" className={status.includes("gespeichert")?"success":""}>{status}</p><button className="save-button" disabled={!dirty||busy} onClick={save}>{busy?<RefreshCw size={18} className="spin"/>:status.includes("gespeichert")&&!dirty?<CircleCheck size={18}/>:<Save size={18}/>} {busy?"Speichert …":"Ergebnisse speichern"}</button></div></TabsContent>}
 </Tabs><footer>Bowlingcenter Oberberg · Hausliga <span>Saison {season.season}</span></footer></main></div>;
}
function GroupSelect({group,setGroup}:{group:number;setGroup:(n:number)=>void}){return <Select value={String(group)} onValueChange={v=>setGroup(Number(v))}><SelectTrigger className="group-select" aria-label="Gruppe auswählen"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">Gruppe 1</SelectItem><SelectItem value="2">Gruppe 2</SelectItem></SelectContent></Select>}
